/**
 * Founder Console — founding seed.
 *
 * Realistic starting state for the organization described in the product
 * brief: five founding officers, ten assignments spanning every status, five
 * deliverables, eight decisions across all decision types, an activity feed,
 * a baseline executive brief, and the eleven current strategic decisions
 * recorded as constitutional activity.
 *
 * Timestamps are fixed ISO strings so the seed is deterministic and the
 * seed-integrity tests are stable.
 */

import {
  ActivityEventType,
  DecisionStatus,
  DecisionType,
  DeliverableType,
  OfficerAssignmentStatus,
  OrganizationHealth,
  PersonType,
  Priority,
  ProbationStatus,
  RelatedEntityType,
  ReviewStatus,
  RoleStatus,
  WorkAssignmentStatus,
} from "@/lib/console/domain/enums"
import type { ConsoleState } from "@/types/console"

// --- Timeline anchors (the brief "morning" is 2026-07-21) -------------------
const T = {
  orgCreated: "2026-07-01T00:00:00.000Z",
  now: "2026-07-21T06:00:00.000Z",
  overnight1: "2026-07-21T02:10:00.000Z",
  overnight2: "2026-07-21T03:40:00.000Z",
  overnight3: "2026-07-21T04:55:00.000Z",
  yesterdayEve: "2026-07-20T18:00:00.000Z",
  yesterdayAm: "2026-07-20T07:30:00.000Z",
  twoDaysAgo: "2026-07-19T09:00:00.000Z",
  weekStart: "2026-07-14T09:00:00.000Z",
  founding: "2026-07-01T09:00:00.000Z",
  priorBriefStart: "2026-07-19T18:00:00.000Z",
  priorBriefEnd: "2026-07-20T18:00:00.000Z",
}

export function createSeedState(): ConsoleState {
  const state: ConsoleState = {
    organization: {
      id: "org-1",
      name: "Intelligent Organizations",
      workingName: "Founder Console",
      mission:
        "Build the operating system for intelligent organizations, beginning with software development as the first domain.",
      status: OrganizationHealth.AttentionRequired,
      createdAt: T.orgCreated,
      updatedAt: T.now,
    },

    people: [
      { id: "person-minh", name: "Minh", personType: PersonType.Human, title: "Product Director" },
      { id: "person-vera", name: "Vera", personType: PersonType.AiOfficer, title: "Executive Assistant" },
      { id: "person-marcus", name: "Marcus", personType: PersonType.AiOfficer, title: "Product Manager" },
      { id: "person-iris", name: "Iris", personType: PersonType.AiOfficer, title: "Chief Product Modeller" },
      { id: "person-theo", name: "Theo", personType: PersonType.AiOfficer, title: "Chief Knowledge Architect" },
      { id: "person-nadia", name: "Nadia", personType: PersonType.AiOfficer, title: "Chief Organizational Architect" },
    ],

    roles: [
      {
        id: "role-director",
        title: "Product Director",
        mission: "Hold final strategic and constitutional authority for the organization.",
        responsibilities: [
          "Set strategic direction",
          "Make constitutional decisions",
          "Approve deliverables and high-impact work",
        ],
        authority: "Final strategic and constitutional authority.",
        boundaries: ["Delegates execution to the Founding Council"],
        reportsToRoleId: null,
        status: RoleStatus.Active,
      },
      {
        id: "role-ea",
        title: "Executive Assistant",
        mission:
          "Protect the Product Director's attention and ensure the organization continuously advances toward agreed outcomes.",
        responsibilities: [
          "Prepare the morning brief",
          "Prioritize executive decisions",
          "Coordinate the Founding Council",
          "Route assignments",
          "Track important risks and blockers",
          "Maintain strategic coherence",
          "Escalate only matters requiring executive judgment",
        ],
        authority: "Coordinates the Founding Council and routes work on the Director's behalf.",
        boundaries: [
          "Does not make constitutional decisions",
          "Escalates matters requiring executive judgment rather than deciding them",
        ],
        reportsToRoleId: "role-director",
        status: RoleStatus.Active,
      },
      {
        id: "role-pm",
        title: "Product Manager",
        mission: "Convert intentions and business outcomes into clear, executable product work.",
        responsibilities: [
          "Translate outcomes into assignments",
          "Define acceptance criteria",
          "Maintain the product backlog",
        ],
        authority: "Owns product definition and sequencing within agreed strategy.",
        boundaries: ["Does not set strategy", "Does not approve its own deliverables"],
        reportsToRoleId: "role-ea",
        status: RoleStatus.Active,
      },
      {
        id: "role-cpm",
        title: "Chief Product Modeller",
        mission:
          "Design the Organizational Twin and its canonical objects, relationships, identity, versioning, and change propagation.",
        responsibilities: [
          "Define canonical objects and relationships",
          "Design identity and versioning",
          "Design change propagation",
        ],
        authority: "Owns the Organizational Twin specification.",
        boundaries: ["Temporary founding role", "Does not own knowledge architecture"],
        reportsToRoleId: "role-ea",
        status: RoleStatus.Temporary,
      },
      {
        id: "role-cka",
        title: "Chief Knowledge Architect",
        mission:
          "Design the Organizational Mind: atomic knowledge, retrieval, context assembly, promotion, reasoning, and forgetting.",
        responsibilities: [
          "Design atomic knowledge model",
          "Design retrieval and context assembly",
          "Define promotion and forgetting policy",
        ],
        authority: "Owns the Organizational Mind architecture.",
        boundaries: ["Does not own the organization model"],
        reportsToRoleId: "role-ea",
        status: RoleStatus.Active,
      },
      {
        id: "role-coa",
        title: "Chief Organizational Architect",
        mission: "Design the universal Organization Engine for human and AI organizations.",
        responsibilities: [
          "Define the universal organization model",
          "Define authority structure and governance",
          "Define capabilities, lifecycle, and evolution",
        ],
        authority: "Owns the universal Organization Engine model.",
        boundaries: ["Aligns with, but does not override, constitutional decisions"],
        reportsToRoleId: "role-ea",
        status: RoleStatus.Active,
      },
    ],

    officerAssignments: [
      { id: "oa-minh", personId: "person-minh", roleId: "role-director", startDate: T.founding, status: OfficerAssignmentStatus.Active, probationStatus: ProbationStatus.Confirmed },
      { id: "oa-ea", personId: "person-vera", roleId: "role-ea", startDate: T.founding, status: OfficerAssignmentStatus.Active, probationStatus: ProbationStatus.Founding },
      { id: "oa-pm", personId: "person-marcus", roleId: "role-pm", startDate: T.founding, status: OfficerAssignmentStatus.Active, probationStatus: ProbationStatus.Founding },
      { id: "oa-cpm", personId: "person-iris", roleId: "role-cpm", startDate: T.founding, status: OfficerAssignmentStatus.Active, probationStatus: ProbationStatus.Probationary },
      { id: "oa-cka", personId: "person-theo", roleId: "role-cka", startDate: T.founding, status: OfficerAssignmentStatus.Active, probationStatus: ProbationStatus.Founding },
      { id: "oa-coa", personId: "person-nadia", roleId: "role-coa", startDate: T.founding, status: OfficerAssignmentStatus.Active, probationStatus: ProbationStatus.Founding },
    ],

    workAssignments: [
      {
        id: "wa-outcome-map",
        title: "Universal Outcome Map for the Organization Engine",
        objective: "Produce the canonical Outcome Map that connects organizational intentions to measurable outcomes.",
        description:
          "Define the outcome taxonomy, the mapping from strategic intent to outcomes, and the linkage to work assignments. This is the backbone the whole Engine sequences against.",
        ownerOfficerAssignmentId: "oa-pm",
        collaboratorIds: ["oa-coa"],
        priority: Priority.High,
        status: WorkAssignmentStatus.InProgress,
        dueDate: "2026-07-28T00:00:00.000Z",
        acceptanceCriteria: [
          "Outcome taxonomy documented with definitions",
          "Intent → outcome → work mapping illustrated end to end",
          "Reviewed against the Organization Model draft",
        ],
        dependencyIds: [],
        linkedOutcomeIds: ["outcome-engine-core"],
        blockedReason: null,
        progress: [
          { at: T.weekStart, note: "Drafted first-pass taxonomy from the strategic decisions." },
          { at: T.yesterdayAm, note: "Aligned outcome layers with the Organization Model draft." },
        ],
        createdBy: "oa-ea",
        createdAt: T.weekStart,
        updatedAt: T.yesterdayAm,
      },
      {
        id: "wa-twin-spec",
        title: "Organizational Twin Specification v0.1",
        objective: "Define the canonical objects, relationships, identity, versioning, and change propagation of the Organizational Twin.",
        description:
          "First formal specification of the Twin. Establishes the shared object model the rest of the platform will reference.",
        ownerOfficerAssignmentId: "oa-cpm",
        collaboratorIds: ["oa-cka"],
        priority: Priority.High,
        status: WorkAssignmentStatus.Review,
        dueDate: "2026-07-22T00:00:00.000Z",
        acceptanceCriteria: [
          "Canonical objects and relationships enumerated",
          "Identity and versioning model defined",
          "Change-propagation approach described",
        ],
        dependencyIds: [],
        linkedOutcomeIds: ["outcome-twin"],
        blockedReason: null,
        progress: [
          { at: T.twoDaysAgo, note: "Completed object model and relationships." },
          { at: T.overnight2, note: "Submitted v0.1 for the Director's review." },
        ],
        createdBy: "oa-ea",
        createdAt: T.weekStart,
        updatedAt: T.overnight2,
      },
      {
        id: "wa-mind-arch",
        title: "Organizational Mind Architecture v0.1",
        objective: "Define atomic knowledge, retrieval, context assembly, promotion, reasoning, and forgetting.",
        description:
          "Architecture for the Organizational Mind. Blocked pending a permission decision on whether project knowledge may be promoted to shared organizational memory.",
        ownerOfficerAssignmentId: "oa-cka",
        collaboratorIds: [],
        priority: Priority.High,
        status: WorkAssignmentStatus.Blocked,
        dueDate: "2026-07-25T00:00:00.000Z",
        acceptanceCriteria: [
          "Atomic knowledge unit defined",
          "Retrieval and context-assembly flow specified",
          "Promotion and forgetting policy proposed",
        ],
        dependencyIds: [],
        linkedOutcomeIds: ["outcome-mind"],
        blockedReason:
          "Awaiting a permission decision on promoting project knowledge to shared memory before the promotion policy can be finalized.",
        progress: [
          { at: T.twoDaysAgo, note: "Drafted atomic knowledge model and retrieval flow." },
          { at: T.yesterdayEve, note: "Raised a permission request; paused on promotion policy." },
        ],
        createdBy: "oa-ea",
        createdAt: T.weekStart,
        updatedAt: T.yesterdayEve,
      },
      {
        id: "wa-org-model",
        title: "Universal Organization Model & Governance Framework",
        objective: "Define the universal organization model, authority structure, capabilities, governance, lifecycle, and evolution framework.",
        description:
          "The foundational model of the Organization Engine that both human and AI organizations instantiate.",
        ownerOfficerAssignmentId: "oa-coa",
        collaboratorIds: ["oa-pm"],
        priority: Priority.Critical,
        status: WorkAssignmentStatus.InProgress,
        dueDate: "2026-07-31T00:00:00.000Z",
        acceptanceCriteria: [
          "Universal organization model documented",
          "Authority and governance structure defined",
          "Lifecycle and evolution framework outlined",
        ],
        dependencyIds: [],
        linkedOutcomeIds: ["outcome-engine-core"],
        blockedReason: null,
        progress: [
          { at: T.weekStart, note: "Outlined the model layers and authority structure." },
          { at: T.overnight1, note: "Completed a first draft of the governance section." },
        ],
        createdBy: "oa-ea",
        createdAt: T.weekStart,
        updatedAt: T.overnight1,
      },
      {
        id: "wa-council-rhythm",
        title: "Establish Founding Council operating rhythm",
        objective: "Define how the Founding Council meets, reports, and escalates.",
        description: "Operating cadence, reporting format, and escalation path for the Council.",
        ownerOfficerAssignmentId: "oa-ea",
        collaboratorIds: [],
        priority: Priority.Medium,
        status: WorkAssignmentStatus.Approved,
        dueDate: null,
        acceptanceCriteria: ["Cadence defined", "Reporting format agreed", "Escalation path documented"],
        dependencyIds: [],
        linkedOutcomeIds: [],
        blockedReason: null,
        progress: [{ at: T.weekStart, note: "Charter approved by the Director." }],
        createdBy: "oa-ea",
        createdAt: T.founding,
        updatedAt: T.weekStart,
      },
      {
        id: "wa-decision-framework",
        title: "Executive decision prioritization framework",
        objective: "Define how decisions are typed, prioritized, and estimated for the Director.",
        description: "Framework the decision queue uses to order and size the Director's decisions.",
        ownerOfficerAssignmentId: "oa-ea",
        collaboratorIds: [],
        priority: Priority.Medium,
        status: WorkAssignmentStatus.Completed,
        dueDate: null,
        acceptanceCriteria: ["Decision types defined", "Priority model defined", "Time-to-decide estimation defined"],
        dependencyIds: [],
        linkedOutcomeIds: [],
        blockedReason: null,
        progress: [{ at: T.overnight3, note: "Framework completed and adopted." }],
        createdBy: "oa-ea",
        createdAt: T.founding,
        updatedAt: T.overnight3,
      },
      {
        id: "wa-taxonomy-spike",
        title: "Outcome Map taxonomy spike",
        objective: "De-risk the Outcome Map by testing three candidate taxonomies.",
        description: "Short spike comparing taxonomy options ahead of the full Outcome Map.",
        ownerOfficerAssignmentId: "oa-pm",
        collaboratorIds: [],
        priority: Priority.Low,
        status: WorkAssignmentStatus.Completed,
        dueDate: null,
        acceptanceCriteria: ["Three taxonomies compared", "Recommendation made"],
        dependencyIds: [],
        linkedOutcomeIds: ["outcome-engine-core"],
        blockedReason: null,
        progress: [{ at: T.overnight1, note: "Spike complete; recommended a layered taxonomy." }],
        createdBy: "oa-ea",
        createdAt: T.weekStart,
        updatedAt: T.overnight1,
      },
      {
        id: "wa-authority-model",
        title: "Authority & lifecycle model draft",
        objective: "Draft the authority delegation and role lifecycle portion of the Organization Model.",
        description: "Focused draft feeding the larger Organization Model assignment.",
        ownerOfficerAssignmentId: "oa-coa",
        collaboratorIds: [],
        priority: Priority.Medium,
        status: WorkAssignmentStatus.Ready,
        dueDate: "2026-07-30T00:00:00.000Z",
        acceptanceCriteria: ["Authority delegation model drafted", "Role lifecycle states defined"],
        dependencyIds: ["wa-org-model"],
        linkedOutcomeIds: ["outcome-engine-core"],
        blockedReason: null,
        progress: [],
        createdBy: "oa-ea",
        createdAt: T.yesterdayAm,
        updatedAt: T.yesterdayAm,
      },
      {
        id: "wa-change-prop",
        title: "Change-propagation prototype",
        objective: "Prototype how a change to one Twin object propagates to dependents.",
        description: "Proposed follow-on once the Twin specification is approved.",
        ownerOfficerAssignmentId: "oa-cpm",
        collaboratorIds: [],
        priority: Priority.Low,
        status: WorkAssignmentStatus.Proposed,
        dueDate: null,
        acceptanceCriteria: ["Propagation rules prototyped", "Edge cases catalogued"],
        dependencyIds: ["wa-twin-spec"],
        linkedOutcomeIds: ["outcome-twin"],
        blockedReason: null,
        progress: [],
        createdBy: "oa-ea",
        createdAt: T.yesterdayAm,
        updatedAt: T.yesterdayAm,
      },
      {
        id: "wa-forgetting-research",
        title: "Forgetting & promotion policy research",
        objective: "Survey approaches to knowledge forgetting and promotion.",
        description: "Superseded by folding the research directly into the Mind Architecture assignment.",
        ownerOfficerAssignmentId: "oa-cka",
        collaboratorIds: [],
        priority: Priority.Low,
        status: WorkAssignmentStatus.Cancelled,
        dueDate: null,
        acceptanceCriteria: ["Approaches surveyed"],
        dependencyIds: [],
        linkedOutcomeIds: ["outcome-mind"],
        blockedReason: null,
        progress: [{ at: T.twoDaysAgo, note: "Cancelled — merged into Mind Architecture v0.1." }],
        createdBy: "oa-ea",
        createdAt: T.weekStart,
        updatedAt: T.twoDaysAgo,
      },
    ],

    deliverables: [
      {
        id: "del-twin-spec",
        assignmentId: "wa-twin-spec",
        title: "Organizational Twin Specification v0.1",
        type: DeliverableType.Specification,
        version: 1,
        summary:
          "First formal specification of the Organizational Twin: canonical objects, relationships, identity, versioning, and change propagation.",
        content:
          "# Organizational Twin Specification v0.1\n\n## Canonical objects\nOrganization, Role, Person, Assignment, Deliverable, Decision, Outcome.\n\n## Relationships\nRoles form a reporting hierarchy. People occupy Roles via time-bounded assignments. Work links to Outcomes.\n\n## Identity & versioning\nEvery canonical object carries a stable id and a monotonically increasing version. Prior versions are retained.\n\n## Change propagation\nA change to an object emits a change event; dependents subscribe and reconcile. v0.1 defines the event shape; propagation rules are prototyped separately.\n\n## Open questions\n- Depth of version history to retain.\n- Whether Outcomes are first-class Twin objects or projections.",
        authorOfficerAssignmentId: "oa-cpm",
        reviewStatus: ReviewStatus.Submitted,
        reviewComments: [],
        supportingEvidence: [
          { label: "Modelling session notes", href: "#", kind: "document" },
          { label: "Object model draft", href: "#", kind: "claude-code" },
        ],
        createdAt: T.overnight2,
        reviewedAt: null,
      },
      {
        id: "del-decision-framework",
        assignmentId: "wa-decision-framework",
        title: "Executive Decision Prioritization Framework",
        type: DeliverableType.Recommendation,
        version: 2,
        summary: "How decisions are typed, prioritized, and time-estimated for the Director.",
        content:
          "# Executive Decision Prioritization Framework\n\nDecisions are typed (approval, question, permission, risk, review, priority, exception, constitutional change), assigned a priority, and estimated in minutes-to-decide so the queue can present the highest-leverage decision first.",
        authorOfficerAssignmentId: "oa-ea",
        reviewStatus: ReviewStatus.Approved,
        reviewComments: [
          { at: T.overnight3, author: "Minh", comment: "Adopt as the queue's default ordering.", outcome: ReviewStatus.Approved },
        ],
        supportingEvidence: [{ label: "Framework rationale", href: "#", kind: "document" }],
        createdAt: T.yesterdayEve,
        reviewedAt: T.overnight3,
      },
      {
        id: "del-taxonomy",
        assignmentId: "wa-taxonomy-spike",
        title: "Outcome Map Taxonomy — Spike Findings",
        type: DeliverableType.Research,
        version: 1,
        summary: "Comparison of three candidate outcome taxonomies with a recommendation for a layered model.",
        content:
          "# Outcome Map Taxonomy — Spike Findings\n\nThree taxonomies were evaluated. A layered taxonomy (strategic → capability → operational outcomes) best supports mapping intent to work and is recommended for the full Outcome Map.",
        authorOfficerAssignmentId: "oa-pm",
        reviewStatus: ReviewStatus.Approved,
        reviewComments: [
          { at: T.overnight1, author: "Minh", comment: "Proceed with the layered taxonomy.", outcome: ReviewStatus.Approved },
        ],
        supportingEvidence: [{ label: "Comparison matrix", href: "#", kind: "codex" }],
        createdAt: T.twoDaysAgo,
        reviewedAt: T.overnight1,
      },
      {
        id: "del-org-model-outline",
        assignmentId: "wa-org-model",
        title: "Universal Organization Model — Draft Outline",
        type: DeliverableType.Plan,
        version: 1,
        summary: "Working outline of the universal organization model and governance framework.",
        content:
          "# Universal Organization Model — Draft Outline\n\n1. Model layers\n2. Authority structure\n3. Capabilities\n4. Governance\n5. Lifecycle & evolution\n\nDraft; not yet submitted for review.",
        authorOfficerAssignmentId: "oa-coa",
        reviewStatus: ReviewStatus.Draft,
        reviewComments: [],
        supportingEvidence: [],
        createdAt: T.overnight1,
        reviewedAt: null,
      },
      {
        id: "del-council-rhythm",
        assignmentId: "wa-council-rhythm",
        title: "Founding Council Operating Rhythm",
        type: DeliverableType.Charter,
        version: 1,
        summary: "Cadence, reporting format, and escalation path for the Founding Council.",
        content:
          "# Founding Council Operating Rhythm\n\nThe Council reports each morning via the executive brief, escalates only decisions requiring executive judgment, and reviews progress against agreed outcomes weekly.",
        authorOfficerAssignmentId: "oa-ea",
        reviewStatus: ReviewStatus.Approved,
        reviewComments: [
          { at: T.weekStart, author: "Minh", comment: "Approved.", outcome: ReviewStatus.Approved },
        ],
        supportingEvidence: [],
        createdAt: T.founding,
        reviewedAt: T.weekStart,
      },
    ],

    decisions: [
      {
        id: "dec-approve-twin",
        title: "Approve Organizational Twin Specification v0.1",
        type: DecisionType.Review,
        priority: Priority.High,
        context: "The Chief Product Modeller has submitted v0.1 of the Organizational Twin specification for review.",
        whyItMatters:
          "The Twin is the shared object model the rest of the platform references. Approving v0.1 unblocks change-propagation work and aligns the Council on canonical objects.",
        recommendation: "Approve v0.1 and open the two listed questions as follow-up work.",
        alternatives: [
          { title: "Request revision", description: "Return for deeper treatment of version-history depth before approval." },
          { title: "Defer", description: "Hold until the Organization Model draft is further along." },
        ],
        expectedImpact: "Unblocks the change-propagation prototype and sets the canonical object model.",
        estimatedDecisionMinutes: 10,
        requestingOfficerAssignmentId: "oa-cpm",
        affectedAssignmentIds: ["wa-twin-spec", "wa-change-prop"],
        supportingEvidence: [{ label: "Twin Specification v0.1", href: "#", kind: "deliverable" }],
        status: DecisionStatus.Waiting,
        resolution: null,
        rationale: null,
        decidedAt: null,
      },
      {
        id: "dec-knowledge-promotion",
        title: "Permission: promote project knowledge to shared memory",
        type: DecisionType.Permission,
        priority: Priority.High,
        context:
          "The Knowledge Architect needs to know whether project-local knowledge may be promoted into shared organizational memory to finalize the promotion policy.",
        whyItMatters:
          "This is currently blocking the Organizational Mind architecture. It also touches the strategic decision that project knowledge remains local unless promotion is approved.",
        recommendation:
          "Grant promotion only via an explicit, logged approval step — consistent with 'knowledge stays local unless promotion is approved'.",
        alternatives: [
          { title: "Deny", description: "Keep all knowledge strictly project-local for now." },
          { title: "Allow automatic promotion", description: "Let officers promote without approval (higher risk)." },
        ],
        expectedImpact: "Unblocks the Organizational Mind architecture and sets the promotion default.",
        estimatedDecisionMinutes: 8,
        requestingOfficerAssignmentId: "oa-cka",
        affectedAssignmentIds: ["wa-mind-arch"],
        supportingEvidence: [{ label: "Draft promotion policy", href: "#", kind: "claude-code" }],
        status: DecisionStatus.Waiting,
        resolution: null,
        rationale: null,
        decidedAt: null,
      },
      {
        id: "dec-ten-year-rule",
        title: "Adopt the 10-Year Rule as a governing principle",
        type: DecisionType.ConstitutionalChange,
        priority: Priority.High,
        context:
          "The Chief Organizational Architect proposes formally adopting the 10-Year Rule: design decisions should hold up over a ten-year horizon.",
        whyItMatters:
          "A constitutional principle shapes every downstream design decision in the Organization Engine and the Twin.",
        recommendation: "Adopt as a constitutional principle and record it in the strategic decision log.",
        alternatives: [
          { title: "Adopt as guidance", description: "Non-binding guidance rather than a constitutional principle." },
          { title: "Defer", description: "Revisit after the Organization Model draft is complete." },
        ],
        expectedImpact: "Sets a durable evaluation lens for all architecture work.",
        estimatedDecisionMinutes: 15,
        requestingOfficerAssignmentId: "oa-coa",
        affectedAssignmentIds: ["wa-org-model"],
        supportingEvidence: [],
        status: DecisionStatus.Waiting,
        resolution: null,
        rationale: null,
        decidedAt: null,
      },
      {
        id: "dec-priority-sequence",
        title: "Sequence: Outcome Map vs Organization Model next",
        type: DecisionType.Priority,
        priority: Priority.Medium,
        context: "Two foundational pieces are progressing in parallel; the Council asks which to prioritize for the next cycle.",
        whyItMatters: "Sequencing affects which officers are on the critical path next week.",
        recommendation: "Prioritize the Organization Model — the Outcome Map depends on its authority structure.",
        alternatives: [
          { title: "Prioritize Outcome Map", description: "Lead with outcomes and retrofit to the model." },
          { title: "Run both", description: "Keep both fully staffed (risks thin coverage)." },
        ],
        expectedImpact: "Clarifies the critical path for the coming cycle.",
        estimatedDecisionMinutes: 5,
        requestingOfficerAssignmentId: "oa-ea",
        affectedAssignmentIds: ["wa-outcome-map", "wa-org-model"],
        supportingEvidence: [],
        status: DecisionStatus.Waiting,
        resolution: null,
        rationale: null,
        decidedAt: null,
      },
      {
        id: "dec-domain-lock",
        title: "Should software development be locked as the first domain?",
        type: DecisionType.Question,
        priority: Priority.Medium,
        context: "The Product Manager asks whether the first domain implementation is firmly software development or provisional.",
        whyItMatters: "Locking the domain focuses the Outcome Map and Engine work; keeping it open preserves generality.",
        recommendation: "Lock software development as the first implementation while keeping the Engine domain-agnostic.",
        alternatives: [{ title: "Keep provisional", description: "Do not commit to a first domain yet." }],
        expectedImpact: "Focuses near-term product work.",
        estimatedDecisionMinutes: 5,
        requestingOfficerAssignmentId: "oa-pm",
        affectedAssignmentIds: ["wa-outcome-map"],
        supportingEvidence: [],
        status: DecisionStatus.Waiting,
        resolution: null,
        rationale: null,
        decidedAt: null,
      },
      {
        id: "dec-blocker-risk",
        title: "Risk: Knowledge Architect blocked may slip the Mind timeline",
        type: DecisionType.Risk,
        priority: Priority.Medium,
        context: "The Organizational Mind assignment has been blocked awaiting the promotion permission decision.",
        whyItMatters: "A prolonged block risks slipping the Mind architecture milestone and idles a founding officer.",
        recommendation: "Resolve the promotion permission decision today to clear the block.",
        alternatives: [{ title: "Reassign", description: "Redirect the officer to unrelated Mind work meanwhile." }],
        expectedImpact: "Protects the Mind architecture timeline.",
        estimatedDecisionMinutes: 5,
        requestingOfficerAssignmentId: "oa-ea",
        affectedAssignmentIds: ["wa-mind-arch"],
        supportingEvidence: [],
        status: DecisionStatus.Waiting,
        resolution: null,
        rationale: null,
        decidedAt: null,
      },
      {
        id: "dec-approve-framework",
        title: "Approve Executive Decision Prioritization Framework",
        type: DecisionType.Approval,
        priority: Priority.Low,
        context: "The EA submitted the decision prioritization framework for adoption.",
        whyItMatters: "Sets how this very queue is ordered.",
        recommendation: "Approve.",
        alternatives: [],
        expectedImpact: "Adopted as the queue's default ordering.",
        estimatedDecisionMinutes: 5,
        requestingOfficerAssignmentId: "oa-ea",
        affectedAssignmentIds: ["wa-decision-framework"],
        supportingEvidence: [{ label: "Framework", href: "#", kind: "deliverable" }],
        status: DecisionStatus.Approved,
        resolution: "approve",
        rationale: "Adopt as the queue's default ordering.",
        decidedAt: T.overnight3,
      },
      {
        id: "dec-probation-exception",
        title: "Exception: skip probation checkpoint for the Chief Product Modeller",
        type: DecisionType.Exception,
        priority: Priority.Low,
        context: "A request to waive the first probation checkpoint given the temporary nature of the role.",
        whyItMatters: "Probation checkpoints are a governance safeguard; exceptions should be deliberate.",
        recommendation: "Defer until after the Twin specification review.",
        alternatives: [
          { title: "Grant", description: "Waive the checkpoint now." },
          { title: "Deny", description: "Keep the checkpoint." },
        ],
        expectedImpact: "Minor; affects governance cadence only.",
        estimatedDecisionMinutes: 5,
        requestingOfficerAssignmentId: "oa-cpm",
        affectedAssignmentIds: [],
        supportingEvidence: [],
        status: DecisionStatus.Deferred,
        resolution: "defer",
        rationale: "Revisit after the Twin specification review.",
        decidedAt: T.yesterdayEve,
      },
    ],

    activity: [
      { id: "ev-1", eventType: ActivityEventType.ConstitutionalDecision, title: "Build the operating system for intelligent organizations", description: "Recorded as a founding strategic decision.", actorId: "oa-minh", relatedEntityType: RelatedEntityType.Organization, relatedEntityId: "org-1", occurredAt: T.founding },
      { id: "ev-2", eventType: ActivityEventType.AssignmentCreated, title: "Universal Outcome Map assignment created", description: "Routed to the Product Manager.", actorId: "oa-ea", relatedEntityType: RelatedEntityType.WorkAssignment, relatedEntityId: "wa-outcome-map", occurredAt: T.weekStart },
      { id: "ev-3", eventType: ActivityEventType.AssignmentCreated, title: "Organizational Twin Specification assignment created", description: "Routed to the Chief Product Modeller.", actorId: "oa-ea", relatedEntityType: RelatedEntityType.WorkAssignment, relatedEntityId: "wa-twin-spec", occurredAt: T.weekStart },
      { id: "ev-4", eventType: ActivityEventType.WorkStarted, title: "Work started on the Organization Model", description: "Chief Organizational Architect began the governance section.", actorId: "oa-coa", relatedEntityType: RelatedEntityType.WorkAssignment, relatedEntityId: "wa-org-model", occurredAt: T.weekStart },
      { id: "ev-5", eventType: ActivityEventType.DeliverableApproved, title: "Founding Council Operating Rhythm approved", description: "Charter approved by the Director.", actorId: "oa-minh", relatedEntityType: RelatedEntityType.Deliverable, relatedEntityId: "del-council-rhythm", occurredAt: T.weekStart },
      { id: "ev-6", eventType: ActivityEventType.DeliverableSubmitted, title: "Taxonomy spike findings submitted", description: "Product Manager submitted the spike findings.", actorId: "oa-pm", relatedEntityType: RelatedEntityType.Deliverable, relatedEntityId: "del-taxonomy", occurredAt: T.twoDaysAgo },
      { id: "ev-7", eventType: ActivityEventType.QuestionRaised, title: "Question raised on first-domain lock", description: "Product Manager asked whether software development is the locked first domain.", actorId: "oa-pm", relatedEntityType: RelatedEntityType.Decision, relatedEntityId: "dec-domain-lock", occurredAt: T.twoDaysAgo },
      { id: "ev-8", eventType: ActivityEventType.OfficerBlocked, title: "Knowledge Architect blocked", description: "Mind architecture paused pending a promotion permission decision.", actorId: "oa-cka", relatedEntityType: RelatedEntityType.WorkAssignment, relatedEntityId: "wa-mind-arch", occurredAt: T.yesterdayEve },
      { id: "ev-9", eventType: ActivityEventType.DecisionRequested, title: "Permission requested: knowledge promotion", description: "Knowledge Architect requested a promotion permission decision.", actorId: "oa-cka", relatedEntityType: RelatedEntityType.Decision, relatedEntityId: "dec-knowledge-promotion", occurredAt: T.yesterdayEve },
      { id: "ev-10", eventType: ActivityEventType.DecisionRequested, title: "Constitutional change proposed: 10-Year Rule", description: "Chief Organizational Architect proposed adopting the 10-Year Rule.", actorId: "oa-coa", relatedEntityType: RelatedEntityType.Decision, relatedEntityId: "dec-ten-year-rule", occurredAt: T.yesterdayEve },
      { id: "ev-11", eventType: ActivityEventType.DeliverableApproved, title: "Taxonomy spike findings approved", description: "Director approved the layered taxonomy recommendation.", actorId: "oa-minh", relatedEntityType: RelatedEntityType.Deliverable, relatedEntityId: "del-taxonomy", occurredAt: T.overnight1 },
      { id: "ev-12", eventType: ActivityEventType.DecisionResolved, title: "Decision prioritization framework approved", description: "Director adopted the framework as the queue's default ordering.", actorId: "oa-minh", relatedEntityType: RelatedEntityType.Decision, relatedEntityId: "dec-approve-framework", occurredAt: T.overnight3 },
      { id: "ev-13", eventType: ActivityEventType.DeliverableSubmitted, title: "Organizational Twin Specification v0.1 submitted", description: "Chief Product Modeller submitted v0.1 for review.", actorId: "oa-cpm", relatedEntityType: RelatedEntityType.Deliverable, relatedEntityId: "del-twin-spec", occurredAt: T.overnight2 },
      { id: "ev-14", eventType: ActivityEventType.DecisionRequested, title: "Review requested: Twin Specification v0.1", description: "Approval of the Twin specification is awaiting the Director.", actorId: "oa-cpm", relatedEntityType: RelatedEntityType.Decision, relatedEntityId: "dec-approve-twin", occurredAt: T.overnight2 },
    ],

    briefs: [
      {
        id: "brief-prior",
        periodStart: T.priorBriefStart,
        periodEnd: T.priorBriefEnd,
        summary: "5 officers active, 3 assignments in progress, 1 completed since the last brief.",
        highlights: ["Completed: Founding Council operating rhythm", "Organization Model governance section underway"],
        risks: ["Organizational Mind work at risk of blocking on a permission decision"],
        decisionsWaiting: 3,
        deliverablesReady: 0,
        organizationHealth: OrganizationHealth.AttentionRequired,
        generatedAt: T.priorBriefEnd,
      },
    ],

    conversation: [],
  }

  return state
}
